### ISSUE TITLE
Problem loading diasend export

### ISSUE THREAD

**Issue by whooze** [gh-davidr/NightscoutLoader#1]
Using latest version, v2.6

Choose a diasend-exported file.
Doing a Load Meter/Pump only
Getting this msg
![image](https://cloud.githubusercontent.com/assets/4024639/22866308/983660fa-f174-11e6-83cc-6a07e30187fd.png)

Any idea what to do?

May the diasend export be different because I'm in sweden?

**Comment by gh-davidr** [comment]
Please confirm that the file contents are in English. 

Tab names should say: "Name and glucose", "CGM",  "Insulin use and carbs", "Insulin pump settings" etc.
First few lines of Name and glucose should say:

Patient ID
Name
Date

etc.

Please confirm.  If the file is in Swedish, there is (I believe) an option to select English before exporting.

Regards
David

**Comment by whooze** [comment]
You are correct, it's in swedish and no - I don't see a way to change language before exporting. 
Should be able to register an english account I hope

**Comment by gh-davidr** [comment]
Please navigate to https://www.diasend.com/en/.
Before logging in there's a language drop down top right.  Change that to UK - English and the whole site will then revert to using English including the exports.

Hope this helps...
