### ISSUE TITLE
NighscoutLoader won't load Medtronic carelink.eu CSV exports

### ISSUE THREAD

**Issue by tubes41** [gh-davidr/NightscoutLoader#5]
Error returned is:
Option selected to load Medtronic file:
xxx.csv
However, this file is in an unrecognised format

I'm suspecting it's a date parsing issue?
I can provide example CSV files if required.

**Comment by gh-davidr** [comment]
Thanks for the feedback.  Please send the CSV files for further analysis:

nightscoutloader at gmail.com

**Comment by tubes41** [comment]
Sent...

**Comment by gh-davidr** [comment]
For issues loading from Medtronic, please use version 2.7.1 from this link here: https://drive.google.com/drive/u/1/folders/0BxlKJmCnE32_dlk5dFg4cTd4UGc

The file can be read successfully with this version.

**Comment by jymT1D** [comment]
[CareLink-Export-Dec2017.csv.zip](https://github.com/gh-davidr/NightscoutLoader/files/1585142/CareLink-Export-Dec2017.csv.zip)
Hello, 
Thanks for this amazing job that you are doing. 
My wife have a g640 minided from medtronic. I try to used your new version but the file it is still unrecognised format. Could you give some tips to make this work with your new version. I send you the file attached.
Thanks again for you amazing job helping other people.

**Comment by gh-davidr** [comment]
Hi,

Thanks for your encouraging message.

Unfortunately, I have no access to Medtronic equipment so rely only on what other users can provide me.  The file export you included was generated with a semi-colon ';' separator whereas the program assumes that the separator should be comma ','.  All other Medtronic Carelink files I've seen use the comma field separator (',').

If you always generate using ',' then the files will load successfully by this application.  I've reattached the file you sent, modifying every ';' and replacing with ','.  All 296 entries can now be read.

[CareLink-Export-Dec2017_comma.zip](https://github.com/gh-davidr/NightscoutLoader/files/1589190/CareLink-Export-Dec2017_comma.zip)

Let me know how you get on.

Thanks
David.
