### ISSUE TITLE
configuration with medtronic 640g cgm

### ISSUE THREAD

**Issue by thomasnightscout** [gh-davidr/NightscoutLoader#8]
HI! I am stuck in the config part where entering the mlab info and the nightscout info... please advise, i have a medtronic CGM not an accucheck...
![captura de pantalla 2018-03-02 a la s 21 47 25](https://user-images.githubusercontent.com/31838831/36936709-6b3453c2-1ece-11e8-9f4b-2f3e0c7a6615.png)

**Comment by gh-davidr** [comment]
Let's resolve config setup via email rather than Github or Facebook.  These platforms are completely open and anyone can see your sensitive details.

Please email to nightscoutloader@gmail.com and I'll respond.

Closing this issue.
