### ISSUE TITLE
Diasend Date Format

### ISSUE THREAD

**Issue by kskandispersonal** [gh-davidr/NightscoutLoader#9]
First, thank you so much for making this app available.  It is especially useful for Omnipod users to get their data imported into Nightscout!

I've come across one issue, but perhaps I am using the app incorrectly... The available date formats in Settings does not include "MM/dd/yyyy HH:mm" which is the format used by Diasend in the USA for exported xls data files.  This is discussed at [openaps/docs#1316](https://github.com/openaps/docs/issues/1316) and at [autotuned gitter](https://gitter.im/openaps/autotune).  

I made a fix in my fork of your dev branch to include this date fomat:
WinSettings.java, line 88
`private String[] m_InputDateFormatList = {"Default", "dd/MM/yy hh:mm", "MM/dd/yy hh:mm", "dd/MM/yy", "MM/dd/yy", "MM/dd/yyyy HH:mm"};`

I'm using IntelliJ rather than Eclipse though so am not sure I should create a PR on this.

**Comment by gh-davidr** [comment]
Thanks for the feedback kskandispersonal - always nice to hear appreciation for the effort involved.
My apologies to you too.  I see you raised an issue many months back when I first uploaded the source code requesting files to build in Eclipse.  I later did this but never responded - however I see you've closed the issue out.

Thanks for diagnosing the issue with your Diasend file upload.  I'll include the extra date format into next build which will also now incorporate CellNovo support.

**Comment by kskandispersonal** [comment]
Thank you!!

**Comment by kskandispersonal** [comment]
Thanks for reviewing and merging!
